model:
  policy_model:
    ckpt: /gscratch/tial/yushihu/human_feedback/t5-large-oracle-1k-train
    input_padding_side: right
    train_generation_kwargs:
      do_sample: True
      top_k: 20
      top_p: null
      temperature: 0.7
    eval_generation_kwargs:
      do_sample: False
      num_beams: 1
  value_model:
    ckpt: t5-base
    freeze_value_model: False
    policy_value_sharing: False
  

reward:
  relevance_model:
    ckpt: /gscratch/tial/yushihu/human_feedback/non_fact_subsent_rm_full_ellen0509
    positive_reward: 0.3
    negative_reward: -0.3
  factuality_model:
    ckpt: /gscratch/tial/yushihu/human_feedback/fact_rm_full_ellen0509
    positive_reward: 0.5
    negative_reward: -0.5
  completeness_model:
    ckpt: /gscratch/tial/yushihu/human_feedback/missing_rm_pref_coverage_full_ellen0509
    mean: -0.44677690555995353
    std: 8.301160619054132
    bias: 0.0
    scale: 0.3

env:
  max_input_len: 1024
  max_generated_len: 200
  train_num_samples_per_input: 4

ppo:
  kl_coef: 0.3
  lam: 0.95
  gamma: 1.0
  pg_coef: 1.0
  vf_coef: 1.0
  cliprange: 0.2
  cliprange_value: 0.2
  whiten_rewards: True

train:
  total_episodes: 80000
  eval_interval: 50
  sampling_batch_size_per_card: 4
  training_batch_size_per_card: 2
  lr: 0.00001
  n_warmup_steps: 100
  n_ppo_epoch_per_rollout: 4
  kl_threshold: 10.0
  clip_grad: False
  max_grad_norm: 0.5
  seed: 42
  cuda_deterministic: True

logging:
  run_name: finegrained_42
  wandb_log: True
  wandb_entity: uwnlp
  wandb_project: asqa_RL
  log_interval: 1
  save_dir: runs